Wed Feb 04 11:33:41 CET 2015 : Apache Derby Network Server - 10.10.1.3 - (1557168) started and ready to accept connections on port 1527
----------------------------------------------------------------
Wed Feb 04 11:33:42 CET 2015:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): instance a816c00e-014b-5427-130c-ffff8fc27e9a 
on database directory /home/jorkut/Dropbox/Universit√†/2 - Laurea Triennale/3 - Terzo anno/Esami da sostenere/Sviluppo applicazioni software/Progetto/Git/UniSvilAppSoft/CryptoHelperDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_25-b17
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
<<<<<<< HEAD
os.version=6.3
derby.system.home=C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Wed Feb 04 11:14:57 CET 2015:
Arresto dell'istanza a816c00e-014b-5415-d2e6-00006960ef3f nella directory del database C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft\CryptoHelperDB con il caricatore di classi sun.misc.Launcher$AppClassLoader@1d44bcfa 
Wed Feb 04 11:14:58 CET 2015 Thread[DRDAConnThread_3,5,main] (DATABASE = CryptoHelperDB), (DRDAID = {2}), Chiusura del database 'CryptoHelperDB'.
----------------------------------------------------------------
Wed Feb 04 11:32:09 CET 2015:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): istanza 560740aa-014b-5415-d2e6-00006960ef3f
sulla directory di database C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft\CryptoHelperDB con caricatore classi sun.misc.Launcher$AppClassLoader@1d44bcfa 
Caricato da file:/C:/Program%20Files/Java/jdk1.8.0_25/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_25-b18
user.dir=C:\Program Files\Java\jdk1.8.0_25\db
os.name=Windows 8.1
os.arch=amd64
os.version=6.3
derby.system.home=C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft
Programma di caricamento classe database avviato - derby.database.classpath=''
=======
os.version=3.13.0-40-generic
derby.system.home=/home/jorkut/Desktop/Sviluppo applicazioni software/Progetto/Git/UniSvilAppSoft
Database Class Loader started - derby.database.classpath=''
Wed Feb 04 11:33:42 CET 2015 Thread[DRDAConnThread_2,5,main] (XID = 181), (SESSIONID = 0), (DATABASE = CryptoHelperDB), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Feb 04 11:33:42 CET 2015 Thread[DRDAConnThread_2,5,main] (DATABASE = CryptoHelperDB), (DRDAID = {1}), Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
>>>>>>> c9bc63024d30101ec58b7a3c2680171b24c294eb
